title: kingkongwu Gitbook
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji